services:
  rag-openapi-pgvector:
    image: 'pgvector/pgvector:pg17'
    environment:
      - 'POSTGRES_DB=rag-openapi-db'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rag-wiremock-spr:
    image: 'wiremock/wiremock:latest'
    command: '--global-response-templating --verbose --jetty-header-buffer-size 16384'
    ports:
      - "9090:8080"
    volumes:
      - ./mock:/home/wiremock
